// artifacts/portfolio/src/components/About.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from "vue";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";

gsap.registerPlugin(ScrollTrigger);

const sectionRef = ref<HTMLElement | null>(null);
let ctx: gsap.Context | null = null;

onMounted(() => {
  ctx = gsap.context(() => {
    gsap.fromTo(".about-left", { opacity: 0, x: -40 }, {
      opacity: 1, x: 0, duration: 1, ease: "power3.out",
      scrollTrigger: { trigger: sectionRef.value, start: "top 72%" },
    });
    gsap.fromTo(".about-right", { opacity: 0, x: 40 }, {
      opacity: 1, x: 0, duration: 1, ease: "power3.out",
      scrollTrigger: { trigger: sectionRef.value, start: "top 72%" },
    });
    gsap.fromTo(".about-stat", { opacity: 0, y: 24 }, {
      opacity: 1, y: 0, duration: 0.6, stagger: 0.12, ease: "power2.out",
      scrollTrigger: { trigger: ".about-stats", start: "top 85%" },
    });
  }, sectionRef.value!);
});
onUnmounted(() => ctx?.revert());
</script>

<template>
  <section id="about" ref="sectionRef" class="about-section">
    <div class="container about-grid">

      <!-- Left -->
      <div class="about-left">
        <p class="section-label">About Me</p>
        <div class="divider" />
        <h3 class="about-heading">Design meets<br />logic.</h3>
        <div class="about-monogram">
          <span>JB</span>
        </div>
      </div>

      <!-- Right -->
      <div class="about-right">
        <div class="about-paragraphs">
          <p>
            I'm a front-end developer passionate about the intersection of
            engineering and design. I build interfaces that don't just work
            flawlessly — they feel <strong>alive</strong>.
          </p>
          <p>
            With a strong eye for visual aesthetics and a solid foundation
            in modern web technologies, I bridge the gap between static
            mockups and interactive reality. Every detail is intentional.
            Every line of code is purposeful.
          </p>
          <p class="quote">
            "Complex systems deserve elegant interfaces."
          </p>
        </div>

        <div class="about-stats">
          <div class="about-stat">
            <div class="about-stat-num">8<span>mo</span></div>
            <div class="about-stat-label">Experience</div>
          </div>
          <div class="about-stat-div" />
          <div class="about-stat">
            <div class="about-stat-num">10<span>+</span></div>
            <div class="about-stat-label">Projects</div>
          </div>
          <div class="about-stat-div" />
          <div class="about-stat">
            <div class="about-stat-num">100<span>%</span></div>
            <div class="about-stat-label">Commitment</div>
          </div>
        </div>
      </div>

    </div>
  </section>
</template>

<style scoped>
.about-section { padding: 8rem 0; background: var(--bg-2); transition: background 0.4s ease; }

.about-grid {
  display: grid; grid-template-columns: 1fr; gap: 4rem;
}
@media (min-width: 1024px) {
  .about-grid { grid-template-columns: 4fr 8fr; align-items: center; }
}

.about-heading {
  font-size: clamp(2.2rem, 4.5vw, 3.8rem); font-weight: 700;
  color: var(--fg); margin-bottom: 2rem; line-height: 1.05;
}

.about-monogram {
  width: 100px; height: 100px;
  border: 1px solid var(--border);
  display: flex; align-items: center; justify-content: center;
  background: var(--bg);
}
.about-monogram span {
  font-family: var(--font-serif);
  font-size: 2.5rem; font-weight: 600;
  color: var(--primary); letter-spacing: 0.05em;
}

.about-paragraphs {
  display: flex; flex-direction: column; gap: 1.5rem;
  font-family: var(--font-serif);
  font-size: 1.1rem; line-height: 1.8;
  color: var(--fg-dim); font-weight: 400; margin-bottom: 3rem;
}
.about-paragraphs strong { color: var(--fg); font-weight: 600; }

.quote {
  font-style: italic; color: var(--muted) !important;
  border-left: 2px solid var(--primary); padding-left: 1.25rem;
  font-size: 1rem !important;
}

.about-stats {
  display: flex; gap: 2.5rem; align-items: center;
  padding-top: 2.5rem; border-top: 1px solid var(--border);
}
.about-stat { text-align: left; }
.about-stat-num {
  font-family: var(--font-display); font-size: 2.4rem;
  font-weight: 700; color: var(--primary); letter-spacing: -0.04em; line-height: 1;
}
.about-stat-num span { font-size: 1.2rem; }
.about-stat-label {
  font-family: var(--font-mono); font-size: 0.58rem;
  letter-spacing: 0.18em; text-transform: uppercase;
  color: var(--muted); margin-top: 5px;
}
.about-stat-div { width: 1px; height: 40px; background: var(--border); }
</style>

// artifacts/portfolio/src/components/About.tsx
import React, { useEffect, useRef } from "react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";

gsap.registerPlugin(ScrollTrigger);

export const About = () => {
  const sectionRef = useRef<HTMLDivElement>(null);
  const textRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const ctx = gsap.context(() => {
      gsap.fromTo(
        ".about-header",
        { opacity: 0, y: 30 },
        {
          opacity: 1,
          y: 0,
          duration: 0.8,
          ease: "power2.out",
          scrollTrigger: {
            trigger: sectionRef.current,
            start: "top 75%",
          }
        }
      );
      gsap.fromTo(
        textRef.current,
        { opacity: 0, y: 50 },
        {
          opacity: 1,
          y: 0,
          duration: 1,
          ease: "power3.out",
          scrollTrigger: {
            trigger: sectionRef.current,
            start: "top 70%",
          }
        }
      );
    }, sectionRef);

    return () => ctx.revert();
  }, []);

  return (
    <section id="about" ref={sectionRef} className="py-32 relative">
      <div className="container mx-auto px-6 md:px-12">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-16 lg:gap-8">

          <div className="about-header lg:col-span-4 flex flex-col justify-between">
            <div>
              <h2 className="text-sm font-medium tracking-widest uppercase text-primary mb-4">About Me</h2>
              <h3 className="text-4xl md:text-5xl font-bold tracking-tight mb-8">Design meets logic.</h3>
            </div>

            <div className="hidden lg:block w-full aspect-square glass-panel border border-border/50 relative overflow-hidden group">
              <div className="absolute inset-0 bg-gradient-to-br from-primary/10 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-700" />
              <div className="absolute inset-0 flex items-center justify-center">
                <span className="text-8xl font-black text-muted/20 uppercase tracking-tighter select-none">JB</span>
              </div>
              <div className="absolute bottom-4 left-4 right-4">
                <div className="font-mono text-[10px] text-primary/50 space-y-1">
                  <div>// front-end developer</div>
                  <div>const passion = "infinite";</div>
                </div>
              </div>
            </div>
          </div>

          <div ref={textRef} className="lg:col-span-8 lg:col-start-5 flex flex-col justify-center">
            <div className="space-y-6 text-lg md:text-xl text-muted-foreground font-light leading-relaxed">
              <p>
                I'm a front-end developer passionate about the intersection of engineering and design.
                I build interfaces that don't just work flawlessly — they feel <span className="text-foreground font-medium">alive</span>.
              </p>
              <p>
                With a strong eye for visual aesthetics and a solid foundation in modern JavaScript frameworks,
                I bridge the gap between static mockups and interactive reality. Every animation is intentional.
                Every line of code is optimized.
              </p>
              <p>
                My philosophy: <span className="text-foreground italic">"Complex systems deserve elegant interfaces."</span>
              </p>
            </div>

            <div className="mt-14 grid grid-cols-3 gap-8 border-t border-border/50 pt-10">
              <div>
                <div className="text-4xl font-bold text-primary mb-1">8mo</div>
                <div className="text-xs text-muted-foreground uppercase tracking-widest">Experience</div>
              </div>
              <div>
                <div className="text-4xl font-bold text-primary mb-1">10+</div>
                <div className="text-xs text-muted-foreground uppercase tracking-widest">Projects</div>
              </div>
              <div>
                <div className="text-4xl font-bold text-primary mb-1">100%</div>
                <div className="text-xs text-muted-foreground uppercase tracking-widest">Commitment</div>
              </div>
            </div>
          </div>

        </div>
      </div>
    </section>
  );
};
