// artifacts/portfolio/src/components/Projects.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from "vue";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";

gsap.registerPlugin(ScrollTrigger);

const sectionRef = ref<HTMLElement | null>(null);
let ctx: gsap.Context | null = null;

interface Project {
  title: string;
  initials: string;
  description: string;
  tags: string[];
  gradient: string;
  accent: string;
}

const PROJECTS: Project[] = [
  {
    title: "Luminary UI",
    initials: "LU",
    description: "A highly customizable component library built for modern design systems, with zero-runtime CSS-in-JS and extensive accessibility support.",
    tags: ["React", "TypeScript", "Storybook"],
    gradient: "linear-gradient(135deg, rgba(139,92,246,0.25) 0%, rgba(59,130,246,0.25) 100%)",
    accent: "rgba(139,92,246,0.5)",
  },
  {
    title: "VelocityDash",
    initials: "VD",
    description: "Real-time analytics dashboard processing millions of events per second with sub-50ms latency UI updates.",
    tags: ["Vue 3", "D3.js", "WebSocket"],
    gradient: "linear-gradient(135deg, rgba(245,166,35,0.25) 0%, rgba(239,68,68,0.2) 100%)",
    accent: "rgba(245,166,35,0.5)",
  },
  {
    title: "Motioncraft",
    initials: "MC",
    description: "An animation toolkit bridging the gap between designers and developers, with visual editors for complex GSAP timelines.",
    tags: ["GSAP", "CSS Houdini", "Vite"],
    gradient: "linear-gradient(135deg, rgba(16,185,129,0.25) 0%, rgba(20,184,166,0.2) 100%)",
    accent: "rgba(16,185,129,0.5)",
  },
  {
    title: "Aperture",
    initials: "AP",
    description: "High-end portfolio generator for professional photographers with dynamic image optimization and fluid masonry layouts.",
    tags: ["Next.js", "Tailwind", "Cloudinary"],
    gradient: "linear-gradient(135deg, rgba(244,63,94,0.25) 0%, rgba(236,72,153,0.2) 100%)",
    accent: "rgba(244,63,94,0.5)",
  },
];

onMounted(() => {
  ctx = gsap.context(() => {
    gsap.fromTo(".projects-header", { opacity: 0, y: 30 }, {
      opacity: 1, y: 0, duration: 0.8, ease: "power2.out",
      scrollTrigger: { trigger: sectionRef.value, start: "top 80%" },
    });
    gsap.utils.toArray<HTMLElement>(".project-card").forEach((card) => {
      gsap.fromTo(card, { opacity: 0, y: 50 }, {
        opacity: 1, y: 0, duration: 0.8, ease: "power3.out",
        scrollTrigger: { trigger: card, start: "top 88%" },
      });
    });
  }, sectionRef.value!);
});
onUnmounted(() => ctx?.revert());
</script>

<template>
  <section id="projects" ref="sectionRef" class="projects-section">
    <div class="container">

      <div class="projects-header">
        <div>
          <p class="section-label">Selected Work</p>
          <h3 class="projects-title">Coming soon.</h3>
        </div>
        <p class="projects-sub">
          Projects are being documented and polished for showcase. Stay tuned.
        </p>
      </div>

      <div class="projects-grid">
        <div
          v-for="project in PROJECTS"
          :key="project.title"
          class="project-card glass"
          :data-testid="`project-card-${project.title}`"
        >
          <!-- Coming soon badge -->
          <div class="cs-badge">
            <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/>
            </svg>
            Soon
          </div>

          <!-- Hover overlay -->
          <div class="cs-overlay">
            <div class="cs-overlay-badge">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/>
              </svg>
              Coming Soon
            </div>
          </div>

          <!-- Gradient placeholder -->
          <div class="project-thumb" :style="{ background: project.gradient }">
            <div class="project-thumb-bg" />
            <span class="project-initials">{{ project.initials }}</span>
          </div>

          <div class="project-body">
            <h4 class="project-title">{{ project.title }}</h4>
            <p class="project-desc">{{ project.description }}</p>
            <div class="project-tags">
              <span v-for="tag in project.tags" :key="tag" class="project-tag">{{ tag }}</span>
            </div>
          </div>
        </div>
      </div>

    </div>
  </section>
</template>

<style scoped>
.projects-section {
  padding: 7rem 0;
  background: rgba(255,255,255,0.01);
}

.projects-header {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
  margin-bottom: 4rem;
}
@media (min-width: 768px) {
  .projects-header {
    flex-direction: row;
    align-items: flex-end;
    justify-content: space-between;
  }
}

.projects-title {
  font-size: clamp(2rem, 4vw, 3.2rem);
  font-weight: 700;
  color: var(--fg);
}
.projects-sub {
  color: var(--fg-dim);
  font-weight: 300;
  max-width: 400px;
  line-height: 1.7;
  font-size: 0.95rem;
}

.projects-grid {
  display: grid;
  grid-template-columns: 1fr;
  gap: 1.5rem;
}
@media (min-width: 768px) { .projects-grid { grid-template-columns: 1fr 1fr; } }

.project-card {
  position: relative;
  overflow: hidden;
  transition: transform 0.4s ease, border-color 0.4s ease, box-shadow 0.4s ease;
}
.project-card:hover {
  transform: translateY(-8px);
  border-color: rgba(245,166,35,0.25);
  box-shadow: 0 20px 60px rgba(0,0,0,0.4);
}

/* Coming soon badge (always visible) */
.cs-badge {
  position: absolute;
  top: 12px;
  right: 12px;
  z-index: 10;
  display: flex;
  align-items: center;
  gap: 5px;
  background: rgba(9,9,12,0.9);
  border: 1px solid rgba(245,166,35,0.3);
  color: var(--primary);
  font-size: 0.6rem;
  font-weight: 600;
  letter-spacing: 0.12em;
  text-transform: uppercase;
  padding: 4px 10px;
  border-radius: 999px;
}

/* Hover overlay */
.cs-overlay {
  position: absolute;
  inset: 0;
  z-index: 20;
  background: rgba(9,9,12,0.65);
  backdrop-filter: blur(4px);
  display: flex;
  align-items: center;
  justify-content: center;
  opacity: 0;
  transition: opacity 0.35s ease;
}
.project-card:hover .cs-overlay { opacity: 1; }
.cs-overlay-badge {
  display: flex;
  align-items: center;
  gap: 8px;
  background: rgba(9,9,12,0.95);
  border: 1px solid rgba(245,166,35,0.4);
  color: var(--primary);
  font-size: 0.75rem;
  font-weight: 700;
  letter-spacing: 0.15em;
  text-transform: uppercase;
  padding: 10px 24px;
  border-radius: 999px;
}

/* Thumbnail */
.project-thumb {
  width: 100%;
  aspect-ratio: 16/9;
  position: relative;
  overflow: hidden;
  display: flex;
  align-items: center;
  justify-content: center;
}
.project-thumb-bg {
  position: absolute;
  inset: 0;
  background: rgba(9,9,12,0.7);
  transition: background 0.4s ease;
}
.project-card:hover .project-thumb-bg { background: rgba(9,9,12,0.5); }
.project-initials {
  font-family: var(--font-display);
  font-size: 4.5rem;
  font-weight: 900;
  color: rgba(255,255,255,0.08);
  letter-spacing: -0.05em;
  position: relative;
  z-index: 1;
  transition: color 0.4s ease;
}
.project-card:hover .project-initials { color: rgba(255,255,255,0.15); }

/* Body */
.project-body { padding: 1.75rem; }
.project-title {
  font-size: 1.3rem;
  font-weight: 700;
  color: var(--fg);
  margin-bottom: 0.75rem;
  transition: color var(--transition);
}
.project-card:hover .project-title { color: var(--primary); }
.project-desc {
  font-size: 0.85rem;
  color: var(--fg-dim);
  font-weight: 300;
  line-height: 1.7;
  margin-bottom: 1.25rem;
}
.project-tags { display: flex; flex-wrap: wrap; gap: 8px; }
.project-tag {
  font-family: var(--font-mono);
  font-size: 0.65rem;
  padding: 4px 12px;
  background: rgba(255,255,255,0.04);
  border: 1px solid var(--border);
  border-radius: 999px;
  color: rgba(239,239,239,0.7);
}
</style>

// artifacts/portfolio/src/components/Projects.tsx
import React, { useEffect, useRef } from "react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { Clock } from "lucide-react";
import { SiReact, SiTypescript, SiVuedotjs, SiD3, SiNextdotjs, SiTailwindcss } from "react-icons/si";

gsap.registerPlugin(ScrollTrigger);

const PROJECTS = [
  {
    title: "Luminary UI",
    description: "A highly customizable component library built for modern design systems. Features zero-runtime CSS-in-JS and extensive accessibility support.",
    tags: ["React", "TypeScript", "Storybook"],
    gradient: "from-purple-500/20 to-blue-500/20",
    accent: "border-purple-500/50",
    initials: "LU",
    tagIcons: [<SiReact key="r" />, <SiTypescript key="t" />, null],
  },
  {
    title: "VelocityDash",
    description: "Real-time analytics dashboard processing millions of events per second with sub-50ms latency UI updates.",
    tags: ["Vue 3", "D3.js", "WebSocket"],
    gradient: "from-amber-500/20 to-orange-500/20",
    accent: "border-amber-500/50",
    initials: "VD",
    tagIcons: [<SiVuedotjs key="v" />, <SiD3 key="d" />, null],
  },
  {
    title: "Motioncraft",
    description: "An animation toolkit bridging the gap between designers and developers, with visual editors for complex GSAP timelines.",
    tags: ["GSAP", "CSS Houdini", "Vite"],
    gradient: "from-emerald-500/20 to-teal-500/20",
    accent: "border-emerald-500/50",
    initials: "MC",
    tagIcons: [null, null, null],
  },
  {
    title: "Aperture",
    description: "High-end portfolio generator for professional photographers with dynamic image optimization and fluid masonry layouts.",
    tags: ["Next.js", "Tailwind", "Cloudinary"],
    gradient: "from-rose-500/20 to-pink-500/20",
    accent: "border-rose-500/50",
    initials: "AP",
    tagIcons: [<SiNextdotjs key="n" />, <SiTailwindcss key="tw" />, null],
  }
];

export const Projects = () => {
  const sectionRef = useRef<HTMLDivElement>(null);
  const cardsRef = useRef<(HTMLDivElement | null)[]>([]);

  useEffect(() => {
    const ctx = gsap.context(() => {
      gsap.fromTo(
        ".projects-header",
        { opacity: 0, y: 30 },
        {
          opacity: 1,
          y: 0,
          duration: 0.8,
          ease: "power2.out",
          scrollTrigger: {
            trigger: sectionRef.current,
            start: "top 80%",
          }
        }
      );

      cardsRef.current.forEach((card) => {
        if (!card) return;
        gsap.fromTo(
          card,
          { opacity: 0, y: 50 },
          {
            opacity: 1,
            y: 0,
            duration: 0.8,
            ease: "power3.out",
            scrollTrigger: {
              trigger: card,
              start: "top 88%",
            }
          }
        );
      });
    }, sectionRef);

    return () => ctx.revert();
  }, []);

  return (
    <section id="projects" ref={sectionRef} className="py-32 bg-muted/5">
      <div className="container mx-auto px-6 md:px-12">
        <div className="projects-header mb-20 flex flex-col md:flex-row md:items-end justify-between gap-8">
          <div>
            <h2 className="text-sm font-medium tracking-widest uppercase text-primary mb-4">Selected Work</h2>
            <h3 className="text-4xl md:text-5xl font-bold tracking-tight">Coming soon.</h3>
          </div>
          <p className="text-muted-foreground max-w-md font-light text-lg">
            These projects are currently being documented and polished for showcase. Stay tuned.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 md:gap-10">
          {PROJECTS.map((project, index) => (
            <div
              key={project.title}
              ref={el => cardsRef.current[index] = el}
              className={`group relative overflow-hidden glass-panel border border-border/50 hover:border-primary/30 transition-all duration-500 hover:-translate-y-2 interactive`}
              data-testid={`project-card-${index}`}
            >
              {/* Coming Soon Overlay */}
              <div className="absolute inset-0 z-20 flex flex-col items-center justify-center backdrop-blur-[3px] bg-background/60 opacity-0 group-hover:opacity-100 transition-opacity duration-400">
                <div className="flex items-center gap-2 text-primary border border-primary/40 px-5 py-2.5 rounded-full bg-background/80">
                  <Clock size={14} />
                  <span className="text-sm font-semibold tracking-widest uppercase">Coming Soon</span>
                </div>
              </div>

              {/* Static Coming Soon badge (always visible) */}
              <div className="absolute top-4 right-4 z-10 flex items-center gap-1.5 bg-background/90 border border-primary/30 px-3 py-1 rounded-full">
                <Clock size={10} className="text-primary" />
                <span className="text-[10px] font-medium tracking-widest uppercase text-primary">Soon</span>
              </div>

              {/* Gradient placeholder */}
              <div className={`w-full aspect-[16/9] bg-gradient-to-br ${project.gradient} relative overflow-hidden flex items-center justify-center`}>
                <div className="absolute inset-0 bg-background/70 group-hover:bg-background/50 transition-colors duration-500" />
                <span className="text-7xl font-black text-foreground/15 tracking-tighter relative z-10">
                  {project.initials}
                </span>
              </div>

              <div className="p-8">
                <h4 className="text-2xl font-bold text-foreground group-hover:text-primary transition-colors mb-3">
                  {project.title}
                </h4>
                <p className="text-muted-foreground mb-6 font-light leading-relaxed text-sm">
                  {project.description}
                </p>
                <div className="flex flex-wrap gap-2">
                  {project.tags.map((tag, ti) => (
                    <span
                      key={tag}
                      className="flex items-center gap-1.5 text-xs font-mono px-3 py-1.5 bg-muted/40 border border-border rounded-full text-foreground/70"
                    >
                      {project.tagIcons[ti] && (
                        <span className="text-primary text-sm">{project.tagIcons[ti]}</span>
                      )}
                      {tag}
                    </span>
                  ))}
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};
